// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/coderunner.proto

package coderunnerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunTestsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	TestCode      string                 `protobuf:"bytes,2,opt,name=test_code,json=testCode,proto3" json:"test_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTestsRequest) Reset() {
	*x = RunTestsRequest{}
	mi := &file_proto_coderunner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTestsRequest) ProtoMessage() {}

func (x *RunTestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coderunner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTestsRequest.ProtoReflect.Descriptor instead.
func (*RunTestsRequest) Descriptor() ([]byte, []int) {
	return file_proto_coderunner_proto_rawDescGZIP(), []int{0}
}

func (x *RunTestsRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RunTestsRequest) GetTestCode() string {
	if x != nil {
		return x.TestCode
	}
	return ""
}

type RunTestsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verdict       string                 `protobuf:"bytes,1,opt,name=verdict,proto3" json:"verdict,omitempty"`
	Output        string                 `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
	TotalTests    int32                  `protobuf:"varint,3,opt,name=total_tests,json=totalTests,proto3" json:"total_tests,omitempty"`
	PassedTests   int32                  `protobuf:"varint,4,opt,name=passed_tests,json=passedTests,proto3" json:"passed_tests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunTestsResponse) Reset() {
	*x = RunTestsResponse{}
	mi := &file_proto_coderunner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunTestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunTestsResponse) ProtoMessage() {}

func (x *RunTestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_coderunner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunTestsResponse.ProtoReflect.Descriptor instead.
func (*RunTestsResponse) Descriptor() ([]byte, []int) {
	return file_proto_coderunner_proto_rawDescGZIP(), []int{1}
}

func (x *RunTestsResponse) GetVerdict() string {
	if x != nil {
		return x.Verdict
	}
	return ""
}

func (x *RunTestsResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

func (x *RunTestsResponse) GetTotalTests() int32 {
	if x != nil {
		return x.TotalTests
	}
	return 0
}

func (x *RunTestsResponse) GetPassedTests() int32 {
	if x != nil {
		return x.PassedTests
	}
	return 0
}

var File_proto_coderunner_proto protoreflect.FileDescriptor

const file_proto_coderunner_proto_rawDesc = "" +
	"\n" +
	"\x16proto/coderunner.proto\x12\n" +
	"coderunner\"B\n" +
	"\x0fRunTestsRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\ttest_code\x18\x02 \x01(\tR\btestCode\"\x88\x01\n" +
	"\x10RunTestsResponse\x12\x18\n" +
	"\averdict\x18\x01 \x01(\tR\averdict\x12\x16\n" +
	"\x06output\x18\x02 \x01(\tR\x06output\x12\x1f\n" +
	"\vtotal_tests\x18\x03 \x01(\x05R\n" +
	"totalTests\x12!\n" +
	"\fpassed_tests\x18\x04 \x01(\x05R\vpassedTests2Z\n" +
	"\x11CodeRunnerService\x12E\n" +
	"\bRunTests\x12\x1b.coderunner.RunTestsRequest\x1a\x1c.coderunner.RunTestsResponseB3Z1github.com/sorenhoang/go-judge/proto;coderunnerpbb\x06proto3"

var (
	file_proto_coderunner_proto_rawDescOnce sync.Once
	file_proto_coderunner_proto_rawDescData []byte
)

func file_proto_coderunner_proto_rawDescGZIP() []byte {
	file_proto_coderunner_proto_rawDescOnce.Do(func() {
		file_proto_coderunner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_coderunner_proto_rawDesc), len(file_proto_coderunner_proto_rawDesc)))
	})
	return file_proto_coderunner_proto_rawDescData
}

var file_proto_coderunner_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_coderunner_proto_goTypes = []any{
	(*RunTestsRequest)(nil),  // 0: coderunner.RunTestsRequest
	(*RunTestsResponse)(nil), // 1: coderunner.RunTestsResponse
}
var file_proto_coderunner_proto_depIdxs = []int32{
	0, // 0: coderunner.CodeRunnerService.RunTests:input_type -> coderunner.RunTestsRequest
	1, // 1: coderunner.CodeRunnerService.RunTests:output_type -> coderunner.RunTestsResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_coderunner_proto_init() }
func file_proto_coderunner_proto_init() {
	if File_proto_coderunner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_coderunner_proto_rawDesc), len(file_proto_coderunner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_coderunner_proto_goTypes,
		DependencyIndexes: file_proto_coderunner_proto_depIdxs,
		MessageInfos:      file_proto_coderunner_proto_msgTypes,
	}.Build()
	File_proto_coderunner_proto = out.File
	file_proto_coderunner_proto_goTypes = nil
	file_proto_coderunner_proto_depIdxs = nil
}
