// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/coderunner.proto

package coderunnerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CodeRunnerService_RunTests_FullMethodName = "/coderunner.CodeRunnerService/RunTests"
)

// CodeRunnerServiceClient is the client API for CodeRunnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CodeRunnerServiceClient interface {
	RunTests(ctx context.Context, in *RunTestsRequest, opts ...grpc.CallOption) (*RunTestsResponse, error)
}

type codeRunnerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCodeRunnerServiceClient(cc grpc.ClientConnInterface) CodeRunnerServiceClient {
	return &codeRunnerServiceClient{cc}
}

func (c *codeRunnerServiceClient) RunTests(ctx context.Context, in *RunTestsRequest, opts ...grpc.CallOption) (*RunTestsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunTestsResponse)
	err := c.cc.Invoke(ctx, CodeRunnerService_RunTests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CodeRunnerServiceServer is the server API for CodeRunnerService service.
// All implementations must embed UnimplementedCodeRunnerServiceServer
// for forward compatibility.
type CodeRunnerServiceServer interface {
	RunTests(context.Context, *RunTestsRequest) (*RunTestsResponse, error)
	mustEmbedUnimplementedCodeRunnerServiceServer()
}

// UnimplementedCodeRunnerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCodeRunnerServiceServer struct{}

func (UnimplementedCodeRunnerServiceServer) RunTests(context.Context, *RunTestsRequest) (*RunTestsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RunTests not implemented")
}
func (UnimplementedCodeRunnerServiceServer) mustEmbedUnimplementedCodeRunnerServiceServer() {}
func (UnimplementedCodeRunnerServiceServer) testEmbeddedByValue()                           {}

// UnsafeCodeRunnerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CodeRunnerServiceServer will
// result in compilation errors.
type UnsafeCodeRunnerServiceServer interface {
	mustEmbedUnimplementedCodeRunnerServiceServer()
}

func RegisterCodeRunnerServiceServer(s grpc.ServiceRegistrar, srv CodeRunnerServiceServer) {
	// If the following call panics, it indicates UnimplementedCodeRunnerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CodeRunnerService_ServiceDesc, srv)
}

func _CodeRunnerService_RunTests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunTestsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CodeRunnerServiceServer).RunTests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CodeRunnerService_RunTests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CodeRunnerServiceServer).RunTests(ctx, req.(*RunTestsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CodeRunnerService_ServiceDesc is the grpc.ServiceDesc for CodeRunnerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CodeRunnerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "coderunner.CodeRunnerService",
	HandlerType: (*CodeRunnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunTests",
			Handler:    _CodeRunnerService_RunTests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/coderunner.proto",
}
